#!/bin/sh
# Start/stop the Newstwister daemon.

### BEGIN INIT INFO
# Provides:          newstwisterd
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Should-Start:      $network
# Should-Stop:       $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Newstwister daemon
# Description:       the Newstwister controller daemon
### END INIT INFO

. /lib/lsb/init-functions

DAEMON=/opt/newstwister/sbin/newstwisterd.py
NODE=/opt/newstwister/sbin/newstwistern.py
PIDFILE=/opt/newstwister/var/run/newstwisterd.pid
LOGFILE=/opt/newstwister/var/log/newstwister/newstwisterd.log
LOGFILESTREAMS=/opt/newstwister/var/log/newstwister/newstwistern.log
WEBPORT=9054
SEARCHPORT=9053
COMMONPORT=9052
SEARCHPATH=/opt/newstwister/sbin/newstwisters.py
COMMONPATH=/opt/newstwister/sbin/newstwisterc.py
SEARCHAUTH=/opt/newstwister/etc/newstwister/oauth/search_auth.py
TWEETPATH=/opt/newstwister/sbin/newstwistert.py
WEBHOST=localhost
SAVEURL="http://localhost:9055/newstwister/tweets/"
USERURL="http://localhost:9055/newstwister/tweet_users/"
CLIENTS=/opt/newstwister/etc/newstwister/allowed.conf
USER=citizendesk
GROUP=citizendesk

# check/touch/chown the log file
# kill all stream client nodes on stop too (killall twister_node)
#
#

test -x $DAEMON || exit 0

case "$1" in
  start)
    # move/roll log files, if they are too big
    touch $LOGFILE
    chown $USER.$GROUP $LOGFILE
    touch $LOGFILESTREAMS
    chown $USER.$GROUP $LOGFILESTREAMS
    touch $PIDFILE
    chown $USER.$GROUP $PIDFILE

    log_daemon_msg "Starting Newstwister daemon"
    log_progress_msg "newstwisterd"

    start-stop-daemon --start --quiet --pidfile $PIDFILE --startas $DAEMON -- \
        -w $WEBHOST -p $WEBPORT -i $PIDFILE -l $LOGFILE -n $NODE -s $SAVEURL \
        -m $LOGFILESTREAMS -t $SEARCHPORT -e $SEARCHPATH -o $SEARCHAUTH \
        -f $TWEETPATH -r $COMMONPORT -c $COMMONPATH -j $USERURL \
        -d -u $USER -g $GROUP -a $CLIENTS || true

    log_end_msg 0
    ;;

  stop)
    log_daemon_msg "Stopping Newstwister daemon"
    log_progress_msg "newstwisterd"
    start-stop-daemon --stop --quiet \
        --pidfile $PIDFILE || true

    killall newstwistern 2> /dev/null || true
    killall newstwisters 2> /dev/null || true
    killall newstwisterc 2> /dev/null || true
    log_end_msg 0
    ;;

  reload)
    # We don't have support for this yet.
    exit 1
    ;;

  restart|force-reload)
    $0 stop
    sleep 1
    $0 start
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|force-reload}"
    exit 1

esac

exit 0
